#ifndef NERVUSDB_H
#define NERVUSDB_H

#pragma once

/* Generated with cbindgen:0.28.0 */

/* This file is generated by cbindgen. Do not edit manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>

#define NDB_OK 0

#define NDB_ERR_INVALID_ARGUMENT 1

#define NDB_ERR_NULL_POINTER 2

#define NDB_ERR_SYNTAX 1001

#define NDB_ERR_EXECUTION 1002

#define NDB_ERR_STORAGE 1003

#define NDB_ERR_COMPATIBILITY 1004

#define NDB_ERR_BUSY 1005

#define NDB_ERR_UNSUPPORTED 1006

#define NDB_ERR_INTERNAL 1099

#define NDB_ERRCAT_NONE 0

#define NDB_ERRCAT_SYNTAX 1

#define NDB_ERRCAT_EXECUTION 2

#define NDB_ERRCAT_STORAGE 3

#define NDB_ERRCAT_COMPATIBILITY 4

#define NDB_STEP_ROW 1

#define NDB_STEP_DONE 2

#define NDB_STEP_ERROR 3

#define NDB_COL_NULL 0

#define NDB_COL_BOOL 1

#define NDB_COL_INT64 2

#define NDB_COL_DOUBLE 3

#define NDB_COL_STRING 4

#define NDB_COL_LIST 5

#define NDB_COL_MAP 6

#define NDB_COL_NODE 7

#define NDB_COL_RELATIONSHIP 8

#define NDB_COL_PATH 9

#define NDB_COL_OTHER 10

typedef struct ndb_db_t {
  uint8_t _private[0];
} ndb_db_t;

typedef struct ndb_result_t {
  uint8_t _private[0];
} ndb_result_t;

typedef struct ndb_txn_t {
  uint8_t _private[0];
} ndb_txn_t;

typedef struct ndb_stmt_t {
  uint8_t _private[0];
} ndb_stmt_t;

int ndb_last_error_code(void);

int ndb_last_error_category(void);

size_t ndb_last_error_message(char *buf, size_t len);

int ndb_open(const char *path, struct ndb_db_t **out_db);

int ndb_open_paths(const char *ndb_path, const char *wal_path, struct ndb_db_t **out_db);

int ndb_close(struct ndb_db_t *db);

int ndb_query(struct ndb_db_t *db,
              const char *cypher,
              const char *params_json,
              struct ndb_result_t **out_result);

int ndb_execute_write(struct ndb_db_t *db,
                      const char *cypher,
                      const char *params_json,
                      uint32_t *out_summary);

int ndb_result_to_json(struct ndb_result_t *result, char **out_json);

void ndb_result_free(struct ndb_result_t *result);

void ndb_string_free(char *s);

int ndb_begin_write(struct ndb_db_t *db, struct ndb_txn_t **out_txn);

int ndb_txn_query(struct ndb_txn_t *txn, const char *cypher, const char *params_json);

int ndb_txn_commit(struct ndb_txn_t *txn);

int ndb_txn_rollback(struct ndb_txn_t *txn);

int ndb_txn_create_node(struct ndb_txn_t *txn,
                        uint64_t external_id,
                        uint32_t label_id,
                        uint32_t *out_node_id);

int ndb_txn_get_or_create_label(struct ndb_txn_t *txn, const char *name, uint32_t *out_label_id);

int ndb_txn_get_or_create_rel_type(struct ndb_txn_t *txn,
                                   const char *name,
                                   uint32_t *out_rel_type_id);

int ndb_txn_create_edge(struct ndb_txn_t *txn, uint32_t src, uint32_t rel, uint32_t dst);

int ndb_txn_tombstone_node(struct ndb_txn_t *txn, uint32_t node);

int ndb_txn_tombstone_edge(struct ndb_txn_t *txn, uint32_t src, uint32_t rel, uint32_t dst);

int ndb_txn_set_node_property(struct ndb_txn_t *txn,
                              uint32_t node,
                              const char *key,
                              const char *value_json);

int ndb_txn_set_edge_property(struct ndb_txn_t *txn,
                              uint32_t src,
                              uint32_t rel,
                              uint32_t dst,
                              const char *key,
                              const char *value_json);

int ndb_txn_remove_node_property(struct ndb_txn_t *txn, uint32_t node, const char *key);

int ndb_txn_remove_edge_property(struct ndb_txn_t *txn,
                                 uint32_t src,
                                 uint32_t rel,
                                 uint32_t dst,
                                 const char *key);

int ndb_txn_set_vector(struct ndb_txn_t *txn, uint32_t node, const float *vector, size_t len);

int ndb_compact(struct ndb_db_t *db);

int ndb_checkpoint(struct ndb_db_t *db);

int ndb_create_index(struct ndb_db_t *db, const char *label, const char *property);

int ndb_search_vector(struct ndb_db_t *db,
                      const float *query,
                      size_t query_len,
                      uint32_t k,
                      struct ndb_result_t **out_result);

int ndb_vacuum(const char *path);

int ndb_backup(const char *path, const char *backup_dir);

int ndb_bulkload(const char *path, const char *nodes_json, const char *edges_json);

int ndb_prepare_read(struct ndb_db_t *db, const char *cypher, struct ndb_stmt_t **out_stmt);

int ndb_prepare_write(struct ndb_db_t *db, const char *cypher, struct ndb_stmt_t **out_stmt);

int ndb_stmt_bind_null(struct ndb_stmt_t *stmt, const char *name);

int ndb_stmt_bind_bool(struct ndb_stmt_t *stmt, const char *name, int value);

int ndb_stmt_bind_int64(struct ndb_stmt_t *stmt, const char *name, int64_t value);

int ndb_stmt_bind_double(struct ndb_stmt_t *stmt, const char *name, double value);

int ndb_stmt_bind_string(struct ndb_stmt_t *stmt, const char *name, const char *value);

int ndb_stmt_bind_list(struct ndb_stmt_t *stmt, const char *name, const char *value_json);

int ndb_stmt_bind_map(struct ndb_stmt_t *stmt, const char *name, const char *value_json);

int ndb_stmt_step(struct ndb_stmt_t *stmt, int *out_state);

size_t ndb_stmt_column_count(struct ndb_stmt_t *stmt);

int ndb_stmt_column_type(struct ndb_stmt_t *stmt, size_t col);

int ndb_stmt_column_int64(struct ndb_stmt_t *stmt, size_t col, int64_t *out_value);

int ndb_stmt_column_double(struct ndb_stmt_t *stmt, size_t col, double *out_value);

int ndb_stmt_column_bool(struct ndb_stmt_t *stmt, size_t col, int *out_value);

int ndb_stmt_column_string(struct ndb_stmt_t *stmt, size_t col, char **out_value);

int ndb_stmt_column_json(struct ndb_stmt_t *stmt, size_t col, char **out_value);

int ndb_stmt_reset(struct ndb_stmt_t *stmt);

int ndb_stmt_finalize(struct ndb_stmt_t *stmt);

int ndb_stmt_write_count(struct ndb_stmt_t *stmt, uint32_t *out_count);

#endif  /* NERVUSDB_H */
